name: Action for ssh
description: Github action for ssh
author: afeiship
inputs: 
  id_rsa:
    description: The id_rsa
    required: true
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install coscli cli
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.id_rsa }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
