name: Action for ssh
description: Github action for ssh
outputs: {}

runs:
  using: "composite"
  steps:
    - name: Install coscli cli
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "$ID_RSA_PUB" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub

    
