name: ssh test workflow
on: [push]
jobs:
  hello:
    name: test ssh
    runs-on: ubuntu-latest
    env:
      ID_RSA_PUB: ${{ secrets.ID_RSA_PUB }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use SSH
        uses: afeiship/action-ssh@master

      - name: Debug
        run: |
          # list dir
          ssh -T ubuntu@111.229.34.137