name: ssh test workflow
on: [push]
jobs:
  hello:
    name: test ssh
    runs-on: ubuntu-latest
    env:
      ID_RSA: ${{ secrets.ID_RSA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use SSH
        uses: afeiship/action-ssh@master

      - name: Debug
        run: |
          ssh_options="-i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"
          remote_commands=(
            "cd ~/github"
            "ls -alh"
          )
          ssh_command="ssh $ssh_options ubuntu@111.229.34.137 '${remote_commands[*]}'"
          $ssh_command
