name: ssh test workflow
on: [push]
jobs:
  hello:
    name: test ssh
    runs-on: ubuntu-latest
    env:
      ID_RSA: ${{ secrets.ID_RSA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use SSH
        uses: afeiship/action-ssh@master

      - name: Debug
        run: |
          ssh ubuntu@111.229.34.137 <<'ENDSSH'
            echo 1234;
            cd ~/github
            ls -alh
          ENDSSH
