name: ssh test workflow
on: [push]
jobs:
  hello:
    name: test ssh
    runs-on: ubuntu-latest
    env:
      ID_RSA: ${{ secrets.ID_RSA }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use SSH
        uses: afeiship/action-ssh@master

      - name: Debug
        run: |
          remote_commands=(
            "cd ~/github"
            "ls -alh"
          )

          # join with &&
          remote_command_string=$(IFS='&&'; echo "${remote_commands[*]}")
          ssh_command="ssh $SSH_OPTIONS ubuntu@111.229.34.137 $remote_command_string"
          $remote_command_string
